language: node_js
services:
  - 'docker'
script:
  - npm run lint
  - npm run build
  - docker build -t tsears/kidtimer .

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN ;
      docker push tsears/kidtimer ;
    fi
